#ifndef _Z_CAVAX_NETWORK_FIELDS
#define _Z_CAVAX_NETWORK_FIELDS

/*
    https://crypto.bi/cavax/    
*/

enum CAVAX_NETWORK_FIELDS {
    CAVAX_FIELD_VERSIONSTR,
    CAVAX_FIELD_NETWORKID,
    CAVAX_FIELD_NODEID,
    CAVAX_FIELD_MYTIME,
    CAVAX_FIELD_IP,
    CAVAX_FIELD_PEERS,
    CAVAX_FIELD_CHAINID,
    CAVAX_FIELD_REQUESTID,
    CAVAX_FIELD_DEADLINE,
    CAVAX_FIELD_CONTAINERID,
    CAVAX_FIELD_CONTAINERBYTES,
    CAVAX_FIELD_CONTAINERIDS,
    CAVAX_FIELD_MULTICONTAINERBYTES,
};

char *cavax_network_field_name(enum CAVAX_NETWORK_FIELDS f);

#endif